# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.4
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: joepolny@gmail.com
author_name: Joe Polny
contract_name: hello_world
preset_name: production
project_name: tealscript_migration
